/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EasyRouteImport } from './routes/easy'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as StartRouteImport } from './routes/start'
import { Route as ParticipationsIndexRouteImport } from './routes/participations.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EasyRoute = EasyRouteImport.update({
  id: '/easy',
  path: '/easy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipationsIndexRoute = ParticipationsIndexRouteImport.update({
  id: '/participations/',
  path: '/participations/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/easy': typeof EasyRoute
  '/explore': typeof ExploreRoute
  '/plan': typeof PlanRoute
  '/start': typeof StartRoute
  '/participations/': typeof ParticipationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/easy': typeof EasyRoute
  '/explore': typeof ExploreRoute
  '/plan': typeof PlanRoute
  '/start': typeof StartRoute
  '/participations': typeof ParticipationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/easy': typeof EasyRoute
  '/explore': typeof ExploreRoute
  '/plan': typeof PlanRoute
  '/start': typeof StartRoute
  '/participations/': typeof ParticipationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/easy' | '/explore' | '/plan' | '/start' | '/participations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/easy' | '/explore' | '/plan' | '/start' | '/participations'
  id:
    | '__root__'
    | '/'
    | '/easy'
    | '/explore'
    | '/plan'
    | '/start'
    | '/participations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EasyRoute: typeof EasyRoute
  ExploreRoute: typeof ExploreRoute
  PlanRoute: typeof PlanRoute
  StartRoute: typeof StartRoute
  ParticipationsIndexRoute: typeof ParticipationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easy': {
      id: '/easy'
      path: '/easy'
      fullPath: '/easy'
      preLoaderRoute: typeof EasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participations/': {
      id: '/participations/'
      path: '/participations'
      fullPath: '/participations/'
      preLoaderRoute: typeof ParticipationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EasyRoute: EasyRoute,
  ExploreRoute: ExploreRoute,
  PlanRoute: PlanRoute,
  StartRoute: StartRoute,
  ParticipationsIndexRoute: ParticipationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
